spring:
  application:
    name: railwaymanagement
  datasource:
    url: jdbc:h2:mem:mydb
#    url: jdbc:h2:file:/data/railwaydemo
    driverClassName: org.h2.Driver
    username: sa
    password: password
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  #  datasource:
  #    url: jdbc:mysql://127.0.0.1:3306/?user=root
  #    username:
  #    password: